tesseract_languages = {
    "English": "eng",
    "French": "fra",
    "Spanish": "spa",
    "German": "deu",
    "Italian": "ita",
    "Portuguese": "por",
    "Dutch": "nld",
    "Russian": "rus",
    "Chinese (Simplified)": "chi_sim",
    "Chinese (Traditional)": "chi_tra",
    "Japanese": "jpn",
    "Korean": "kor",
    "Arabic": "ara",
    "Hindi": "hin",
    "Turkish": "tur",
    "Thai": "tha",
    "Hebrew": "heb",
    "Vietnamese": "vie",
    "Greek": "ell",
    "Czech": "ces",
    "Polish": "pol",
    "Swedish": "swe",
    "Hungarian": "hun",
    "Danish": "dan",
    "Finnish": "fin",
    "Romanian": "ron",
    "Bulgarian": "bul",
    "Malay": "msa",
    "Indonesian": "ind",
    "Ukrainian": "ukr"
}



google_translate_languages = {
    "English": "en",
    "French": "fr",
    "Spanish": "es",
    "German": "de",
    "Italian": "it",
    "Portuguese": "pt",
    "Dutch": "nl",
    "Russian": "ru",
    "Chinese (Simplified)": "zh-CN",
    "Chinese (Traditional)": "zh-TW",
    "Japanese": "ja",
    "Korean": "ko",
    "Arabic": "ar",
    "Hindi": "hi",
    "Turkish": "tr",
    "Thai": "th",
    "Hebrew": "iw",
    "Vietnamese": "vi",
    "Greek": "el",
    "Czech": "cs",
    "Polish": "pl",
    "Swedish": "sv",
    "Hungarian": "hu",
    "Danish": "da",
    "Finnish": "fi",
    "Romanian": "ro",
    "Bulgarian": "bg",
    "Malay": "ms",
    "Indonesian": "id",
    "Ukrainian": "uk"
}

language_tool_languages = {
    "English": "en",
    "French": "fr",
    "Spanish": "es",
    "German": "de",
    "Italian": "it",
    "Portuguese": "pt",
    "Dutch": "nl",
    "Russian": "ru",
    "Chinese (Simplified)": "zh-CN",
    "Chinese (Traditional)": "zh-TW",
    "Japanese": "ja",
    "Korean": "ko",
    "Arabic": "ar",
    "Hindi": "hi",
    "Turkish": "tr",
    "Thai": "th",
    "Hebrew": "he",
    "Vietnamese": "vi",
    "Greek": "el",
    "Czech": "cs",
    "Polish": "pl",
    "Swedish": "sv",
    "Hungarian": "hu",
    "Danish": "da",
    "Finnish": "fi",
    "Romanian": "ro",
    "Bulgarian": "bg",
    "Malay": "ms",
    "Indonesian": "id",
    "Ukrainian": "uk"
}


